name: Test

on:
 push:
   branches: [main, develop]
 pull_request:
   branches: [main]

jobs:
 test:
   runs-on: ubuntu-latest
   services:
     postgres:
       image: postgres:16.5
       env:
         POSTGRES_PASSWORD: testpass
         POSTGRES_USER: testuser
         POSTGRES_DB: test_db
       ports:
         - 5432:5432
       options: >-
         --health-cmd pg_isready
         --health-interval 10s
         --health-timeout 5s
         --health-retries 5

   steps:
     - uses: actions/checkout@v4
     - uses: oven-sh/setup-bun@v2
       with:
         bun-version: 1.2.21

     - name: Install dependencies
       run: bun install

     - name: Setup test DB
       run: |
         PGPASSWORD=testpass psql -h localhost -U testuser -d test_db < scripts/schema.sql

     - name: Run tests
       env:
         DB_HOST: localhost
         DB_PORT: 5432
         DB_NAME: test_db
         DB_USER: testuser
         DB_PASSWORD: testpass
       run: |
         bun test

     - name: Test API endpoints
       run: |
         bun run src/api/endpoints.ts &
         sleep 5
         curl -f http://localhost:3002/health
         curl -f http://localhost:3002/stats
